name: "Build Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-24.04-arm # use ubuntu-24.04 when building x86 or riscv64
    steps:
      - uses: armbian/build@main
        with:
          armbian_token:     "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:   "noble"                        # userspace
          armbian_target:    "build"                        # build=image, kernel=kernel
          armbian_board:     "onecloud"                   # build target
