name: Build Armbian for OneCloud

on:
  # 允许你手动在 Actions 标签页中触发此 workflow
  workflow_dispatch:
  # 也可以设置为在你 push 到 main 分支时自动触发
  # push:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Armbian source code
        uses: actions/checkout@v4
        with:
          repository: armbian/build
          # 使用 25.05 分支
          ref: 'v25.05'

      - name: Prepare build environment and compile
        run: |
          # 禁用 apt-daily.service 来避免在安装依赖时出现锁文件问题
          sudo systemctl stop apt-daily.timer
          sudo systemctl stop apt-daily.service
          sudo systemctl stop apt-daily-upgrade.timer
          sudo systemctl stop apt-daily-upgrade.service
          
          # 更新软件包列表并安装编译所需的依赖
          sudo apt-get update
          sudo apt-get -y install git build-essential ccache gcc g++ make
          
          # 开始编译
          # BOARD: 指定设备为 onecloud
          # BRANCH: 指定内核分支，通常为 current 或 legacy
          # BUILD_DESKTOP: "no" 表示不构建桌面环境
          # BUILD_MINIMAL: "yes" 表示构建 minimal 镜像
          # RELEASE: 指定发行的代号，例如 bookworm
          ./compile.sh BOARD=onecloud BRANCH=current BUILD_MINIMAL=yes RELEASE=bookworm

      - name: Upload artifact
        # 编译成功后，将生成的镜像文件上传到 GitHub Actions 的 afrtifacts 中
        uses: actions/upload-artifact@v4
        with:
          name: armbian-onecloud-minimal-image
          # Armbian 的输出文件通常在 output/images 目录下
          path: output/images/*
