name: Build Armbian for OneCloud

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential debootstrap

      - name: Build Armbian
        run: |
          # 下载 Armbian 构建脚本
          git clone --depth=1 https://github.com/armbian/build.git
          cd build

          # 配置构建参数
          ./compile.sh config

          # 选择设备型号 (根据实际情况修改)
          ./compile.sh target onecloud

          # 开始编译
          ./compile.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: armbian-image
          path: output/images/*.img